// Generated by Wrangler by running `wrangler types`

interface Env {
  USER_SERVICE_URL: string;
  EXPENSE_SERVICE_URL: string;
  REQUEST_TIMEOUT_MS: string;
  SCHEMA_CACHE_TTL_MS: string;
  USER_SERVICE_WORKER: Fetcher;
  EXPENSE_SERVICE_WORKER: Fetcher;
}
