# .meshrc.yml
sources:
  - name: UserService
    handler:
      graphql:
        endpoint: "https://user-service.vinodh-jeevanantham.workers.dev/graphql"
        method: POST
        operationHeaders:
          Content-Type: "application/json"
          Accept: "application/json"
  - name: ExpenseService
    handler:
      graphql:
        endpoint: "https://expense-service.vinodh-jeevanantham.workers.dev/graphql"
        method: POST
        operationHeaders:
          Content-Type: "application/json"
          Accept: "application/json"

additionalTypeDefs: |
  extend type User {
    expenses: [Expense!]!
  }
  extend type Expense {
    user: User!
  }

additionalResolvers:
  - "./src/additional-resolvers.ts"

serve:
  cors:
    origin: "*"
    credentials: true
  playground: true